---
pages:
- products.md
hide_body: false
fields:
- type: text
  label: Product Title
  name: product_title
- type: file
- type: textarea
  name: product_description
  label: Product Description
  config:
    wysiwyg: true
